services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: goodfood_auth
    ports: ["5433:5432"]   # Ã©vite conflit local
    volumes: ["db_data:/var/lib/postgresql/data"]
volumes: { db_data: {} }
